export H="/mnt/$HOME"
export EDITOR=micro
export QT_QPA_PLATFORMTHEME=qt5ct
export LIBVA_DRIVER_NAME=iHD
export npm_config_prefix="$HOME/.local"
export GOPATH="$H/Go"
export BALLERINA_HOME="$HOME/.local/lib/ballerina"
export PATH="$HOME/.local/share/slfbin/bin:$HOME/.local/bin:$GOPATH/bin:$BALLERINA_HOME/bin:$PATH"
#. "$HOME/.cargo/env"
