# Configuration file for NetworkManager.
# See "man 5 NetworkManager.conf" for details.

[main]
dns=systemd-resolved

# [ipv4]
# dns=86.54.11.1#protective.joindns4.eu;86.54.11.201#protective.joindns4.eu;
# ignore-auto-dns=true
# method=auto
# 
# [ipv6]
# addr-gen-mode=stable-privacy
# dns=2a13:1001::86:54:11:1#protective.joindns4.eu;2a13:1001::86:54:11:201#protective.joindns4.eu;
# ignore-auto-dns=true
# method=auto
